apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  restartPolicy: Always
  containers:
  - name: storage-pod
    image: "k8s.gcr.io/busybox"
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
      - name: vol
        mountPath: /data 
        mountPropagation: "HostToContainer"
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: storage-pvc

